# Generated by Django 5.0.14 on 2026-08-25 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('milestone_type', models.CharField(choices=[('SKILL', 'Skill Milestone'), ('COURSE', 'Course Completion'), ('SESSION', 'Session Completed'), ('CERTIFICATION', 'Certification'), ('PROJECT', 'Project Completed'), ('MATCH', 'Mentor Matched'), ('CUSTOM', 'Custom Milestone')], default='CUSTOM', max_length=20, verbose_name='milestone type')),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='achieved at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'milestone',
                'verbose_name_plural': 'milestones',
                'db_table': 'milestones',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('courses_in_progress', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_lesson_time_minutes', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('total_session_minutes', models.PositiveIntegerField(default=0)),
                ('skills_assessed', models.PositiveIntegerField(default=0)),
                ('average_skill_level', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('milestones_achieved', models.PositiveIntegerField(default=0)),
                ('learning_path_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, verbose_name='snapshot date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'progress snapshot',
                'verbose_name_plural': 'progress snapshots',
                'db_table': 'progress_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rated_level', models.IntegerField(blank=True, choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], null=True, verbose_name='self rated level')),
                ('assessed_level', models.IntegerField(blank=True, choices=[(1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], null=True, verbose_name='assessed level')),
                ('assessment_type', models.CharField(choices=[('SELF', 'Self Assessment'), ('MENTOR', 'Mentor Assessment'), ('PEER', 'Peer Assessment'), ('AUTO', 'Automated Assessment')], default='SELF', max_length=20, verbose_name='assessment type')),
                ('evidence', models.TextField(blank=True, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='assessed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'skill assessment',
                'verbose_name_plural': 'skill assessments',
                'db_table': 'skill_assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='target completion date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='careers.career', verbose_name='career')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_path_students', to='careers.roadmapstage', verbose_name='current stage')),
            ],
            options={
                'verbose_name': 'learning path',
                'verbose_name_plural': 'learning paths',
                'db_table': 'learning_paths',
                'ordering': ['-started_at'],
            },
        ),
    ]
