# Generated by Django 5.0.14 on 2026-08-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acadbot_progress', '0001_initial'),
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='careers.career', verbose_name='career'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='careers.career', verbose_name='career'),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_given', to=settings.AUTH_USER_MODEL, verbose_name='assessed by'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='career_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='careers.careerskill', verbose_name='career skill'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['student', 'career'], name='milestones_student_2d2d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['milestone_type'], name='milestones_milesto_a6027e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progresssnapshot',
            unique_together={('student', 'career', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['student', 'career_skill'], name='skill_asses_student_4a7c94_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['assessed_at'], name='skill_asses_assesse_fa49e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillassessment',
            unique_together={('student', 'career_skill', 'assessment_type')},
        ),
    ]
