# Generated by Django 5.0.14 on 2026-08-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('module_number', models.PositiveIntegerField(default=1, verbose_name='module number')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='duration (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='careers.career', verbose_name='career')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['career', 'module_number', 'order'],
                'unique_together': {('career', 'module_number', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='progress percent')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='last accessed at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content_html', models.TextField(blank=True, verbose_name='content (HTML)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='duration (minutes)')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('quiz_question', models.TextField(blank=True, verbose_name='quiz question')),
                ('quiz_options', models.JSONField(blank=True, default=list, verbose_name='quiz options')),
                ('quiz_correct_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='quiz correct index')),
                ('quiz_feedback', models.TextField(blank=True, verbose_name='quiz feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lessons',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('quiz_answered', models.PositiveIntegerField(blank=True, null=True, verbose_name='quiz answered')),
                ('quiz_correct', models.BooleanField(blank=True, null=True, verbose_name='quiz correct')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='time spent (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment', verbose_name='enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress',
                'db_table': 'lesson_progress',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
