# Generated by Django 5.0.14 on 2026-09-30 01:33

import apps.courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_reviewed',
            field=models.BooleanField(default=False, verbose_name='content reviewed'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.courses.models._generate_certificate_code, max_length=32, unique=True, verbose_name='code')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('score', models.PositiveIntegerField(verbose_name='score')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
