# Generated by Django 5.0.14 on 2026-08-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_schedule', models.JSONField(blank=True, default=dict, verbose_name='preferred schedule')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='matched at')),
                ('preferred_careers', models.ManyToManyField(blank=True, related_name='match_requests', to='careers.career', verbose_name='preferred careers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'match request',
                'verbose_name_plural': 'match requests',
                'db_table': 'match_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('compatibility_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='compatibility score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_mentor', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_student', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.matchrequest', verbose_name='match request')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='compatibility score')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_mentors', to='matching.matchrequest', verbose_name='match request')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_matches', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
            ],
            options={
                'verbose_name': 'mentor match suggestion',
                'verbose_name_plural': 'mentor match suggestions',
                'db_table': 'mentor_matches',
                'ordering': ['-compatibility_score'],
                'unique_together': {('match_request', 'mentor')},
            },
        ),
    ]
