# Generated by Django 5.0.14 on 2026-08-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('meeting_link', models.URLField(blank=True, verbose_name='meeting link')),
                ('meeting_id', models.CharField(blank=True, max_length=100, verbose_name='meeting ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('student_notes', models.TextField(blank=True, verbose_name='student notes')),
                ('mentor_notes', models.TextField(blank=True, verbose_name='mentor notes')),
                ('feedback_student', models.TextField(blank=True, verbose_name='student feedback')),
                ('feedback_mentor', models.TextField(blank=True, verbose_name='mentor feedback')),
                ('rating_student', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='student rating')),
                ('rating_mentor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mentor rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='matching.match', verbose_name='match')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_mentor', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_student', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('STUDENT', 'Student Feedback'), ('MENTOR', 'Mentor Feedback')], max_length=20, verbose_name='feedback type')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='areas for improvement')),
                ('additional_comments', models.TextField(blank=True, verbose_name='additional comments')),
                ('is_shared', models.BooleanField(default=True, verbose_name='shared with other party')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback_given', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_feedback', to='acadbot_sessions.session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'session feedback',
                'verbose_name_plural': 'session feedback',
                'db_table': 'session_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20, verbose_name='frequency')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('occurrences_count', models.PositiveIntegerField(default=0, verbose_name='occurrences count')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='acadbot_sessions.session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'session recurrence',
                'verbose_name_plural': 'session recurrences',
                'db_table': 'session_recurrences',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='recurring')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='specific date')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'db_table': 'availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('mentor', 'day_of_week', 'start_time', 'specific_date')},
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['student', 'status'], name='sessions_student_56581d_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['mentor', 'status'], name='sessions_mentor__a91380_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['scheduled_at', 'status'], name='sessions_schedul_8af9de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together={('session', 'author', 'feedback_type')},
        ),
    ]
