# Generated by Django 5.0.14 on 2026-08-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10, verbose_name='icon')),
                ('tag', models.CharField(help_text='Short tagline', max_length=50, verbose_name='tag')),
                ('color', models.CharField(help_text='Hex color code', max_length=7, verbose_name='color')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'career',
                'verbose_name_plural': 'careers',
                'db_table': 'careers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_core', models.BooleanField(default=True, verbose_name='core skill')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='careers.career', verbose_name='career')),
            ],
            options={
                'verbose_name': 'career skill',
                'verbose_name_plural': 'career skills',
                'db_table': 'career_skills',
                'ordering': ['career', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10, verbose_name='difficulty')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='careers.career', verbose_name='career')),
            ],
            options={
                'verbose_name': 'interview question',
                'verbose_name_plural': 'interview questions',
                'db_table': 'interview_questions',
                'ordering': ['career', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('estimated_weeks', models.PositiveIntegerField(default=0, verbose_name='estimated weeks')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_stages', to='careers.career', verbose_name='career')),
            ],
            options={
                'verbose_name': 'roadmap stage',
                'verbose_name_plural': 'roadmap stages',
                'db_table': 'roadmap_stages',
                'ordering': ['career', 'order'],
            },
        ),
    ]
